# Generated by Django 3.1.3 on 2020-11-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_merge_20201106_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(null=True, upload_to='main_app/static/images'),
        ),
    ]
