# Generated by Django 3.1.3 on 2020-11-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='future_cities',
            field=models.TextField(blank=True),
        ),
    ]
